Update bam2bed

diff --git a/scripts/bam2bed b/scripts/bam2bed
--- a/scripts/bam2bed
+++ b/scripts/bam2bed
@@ -6,7 +6,7 @@ usage() {
   exit 1
 }
 
-while getopts ":t:" opt; do
+while getopts ":t:m:" opt; do
   case $opt in
   t)
     NTHREADS=$OPTARG
@@ -46,10 +46,10 @@ bam2bed(){
   INPUT=$1
   MEMPERTHREAD=$2
   # check if file exists
-  if [[ ! -f $f ]]; then echo "file \"$f\" not found"; exit 1; fi
+  if [[ ! -f $INPUT ]]; then echo "file \"$INPUT\" not found"; exit 1; fi
   
   # check input is a fastq
-  if [[ $f != *.bam ]]; then echo "input is not a bam file"; exit 1; fi
+  if [[ $INPUT != *.bam ]]; then echo "input is not a bam file"; exit 1; fi
   
   UCOUNT=$(samtools view $INPUT | cut -f 1 | head -n 1000 | sort | uniq | wc -l)
   
@@ -59,7 +59,7 @@ bam2bed(){
     PAIRED=0
   fi 
   
-  BASE="$(basename $f | sed 's/\.bam$//g')"
+  BASE="$(basename $INPUT | sed 's/\.bam$//g')"
   OUTPUT=${BASE}.bed
   
   #if [[ $PAIRED -eq 1 ]]; then
