Update dedup

diff --git a/scripts/dedup b/scripts/dedup
--- a/scripts/dedup
+++ b/scripts/dedup
@@ -43,10 +43,10 @@ dedup(){
   INPUT=$1
   
   # check if file exists
-  if [[ ! -f $f ]]; then echo "file \"$f\" not found"; exit 1; fi
+  if [[ ! -f $INPUT ]]; then echo "file \"$INPUT\" not found"; exit 1; fi
   
   # check input is a fastq
-  if [[ $f != *.bam ]]; then echo "input is not a bam file"; exit 1; fi
+  if [[ $INPUT != *.bam ]]; then echo "input is not a bam file"; exit 1; fi
   
   UCOUNT=$(samtools view $INPUT | cut -f 1 | head -n 1000 | sort | uniq | wc -l)
   
@@ -56,12 +56,14 @@ dedup(){
     PAIRARG="-s"
   fi 
   
-  BASE="$(basename $f | sed 's/\.bam$//g')"
+  BASE="$(basename $INPUT | sed 's/\.bam$//g')"
   OUTPUT=${BASE}_rmdup.bam
   LOGFILE=${BASE}_rmdup.bam.log
   
   samtools rmdup $PAIRARG $INPUT $OUTPUT 2> $LOGFILE
   echo $OUTPUT
 }
+
+export -f dedup
 
 parallel --will-cite -k -j $NTHREADS "dedup {}" ::: $INPUT
