Update filtersort

diff --git a/scripts/filtersort b/scripts/filtersort
--- a/scripts/filtersort
+++ b/scripts/filtersort
@@ -44,9 +44,9 @@ filtersort(){
   MEMPERTHREAD=$2
   
   # check if file exists
-  if [[ ! -f $f ]]; then echo "fastq file \"$f\" not found"; exit 1; fi
+  if [[ ! -f $f ]]; then echo "file \"$f\" not found"; exit 1; fi
   # check input is a fastq
-  if [[ $f != *.fastq ]] || [[ $f != *.fq ]] || [[ $f != *.gz ]]; then echo "input is not a fastq"; exit 1; fi
+  if [[ $f != *.bam ]]; then echo "input is not a bam file"; exit 1; fi
      
   BASE="$(basename $f | sed 's/\.bam$//g')"
   OUTPUT=${BASE}_q20_sort.bam
