Update filtersort

diff --git a/scripts/filtersort b/scripts/filtersort
--- a/scripts/filtersort
+++ b/scripts/filtersort
@@ -6,23 +6,26 @@ usage() {
   exit 1
 }
 
-while getopts ":t:" opt; do
+while getopts ":t:m:" opt; do
   case $opt in
   t)
     NTHREADS=$OPTARG
-   ;;
+    ;;
+  m)
+    MEMPERTHREAD=$OPTARGS
+    ;;
   \?)
-   echo "Invalid option: -$OPTARG" >&2
-   usage
-   ;;
+    echo "Invalid option: -$OPTARG" >&2
+    usage
+    ;;
   [?])
-   usage
-   ;;
+    usage
+    ;;
   :)
-   echo "Option -$OPTARG requires an argument." >&2
-   echo "" >&2
-   usage
-   ;;
+    echo "Option -$OPTARG requires an argument." >&2
+    echo "" >&2
+    usage
+    ;;
   esac
 done
 
@@ -44,14 +47,14 @@ filtersort(){
   MEMPERTHREAD=$2
   
   # check if file exists
-  if [[ ! -f $f ]]; then echo "file \"$f\" not found"; exit 1; fi
+  if [[ ! -f $INPUT ]]; then echo "file \"$INPUT\" not found"; exit 1; fi
   # check input is a fastq
-  if [[ $f != *.bam ]]; then echo "input is not a bam file"; exit 1; fi
+  if [[ $INPUT != *.bam ]]; then echo "input is not a bam file"; exit 1; fi
      
-  BASE="$(basename $f | sed 's/\.bam$//g')"
+  BASE="$(basename $INPUT | sed 's/\.bam$//g')"
   OUTPUT=${BASE}_q20_sort.bam
   
-  samtools view -bq 20 $f | samtools sort -m $MEMPERTHREAD -T $OUTPUT - > ${OUTPUT}
+  samtools view -bq 20 $INPUT | samtools sort -m $MEMPERTHREAD -T $OUTPUT - > ${OUTPUT}
   echo $OUTPUT 
 }
 
