Update normalize

diff --git a/scripts/normalize b/scripts/normalize
--- a/scripts/normalize
+++ b/scripts/normalize
@@ -61,10 +61,10 @@ iqrn(){
   Q3=$(echo 3*$NUMLINES/4 | bc)
   ST=$(sort -k4,4n $BG | \
     awk -v q1=$Q1 -v q2=$Q2 -v q3=$Q3 '{if(NR==q1){Q1=$4};if(NR==q2){Q2=$4};if(NR==q3){Q3=$4}}END{print Q3-Q1,Q2}')
-  REFIQR=5
+  REFIQR=5.5
   IQR=$(echo $ST | cut -d ' ' -f 1)
   MDN=$(echo $ST | cut -d ' ' -f 2)
-  awk -v refiqr=$REFIQR -v mdn=$MDN -v iqr=$IQR 'BEGIN{scalar=refiqr/iqr)} {print $1,$2,$3,($4-mdn)*scalar}' OFS='\t' > $OUTPUT
+  awk -v refiqr=$REFIQR -v mdn=$MDN -v iqr=$IQR 'BEGIN{scalar=refiqr/iqr} {print $1,$2,$3,($4-mdn)*scalar}' OFS='\t' $BG > $OUTPUT
 
 }
 
@@ -96,7 +96,7 @@ export -f iqrn
 export -f normalize
 
 if [[ ! -f $REFERENCE ]]; then
-  >&2 echo "file \"$REFERENCE\" not found, making an average distribution after IQR-normalizing input bedGraphs"
+  >&2 echo "reference file not found, making an average distribution after IQR-normalizing input bedGraphs"
   INPUTI=$(parallel --no-notice -k -j $NTHREADS "iqrn {}" ::: $INPUT)
   tmpref="$(mktemp).bg"
   cat $INPUTI > $tmprefi
