Update samstats

diff --git a/scripts/samstats b/scripts/samstats
--- a/scripts/samstats
+++ b/scripts/samstats
@@ -42,11 +42,11 @@ INPUT=$@
 samstats(){
   INPUT=$1
   # check if file exists
-  if [[ ! -f $f ]]; then echo "file \"$f\" not found"; exit 1; fi
+  if [[ ! -f $f ]]; then >&2 echo "file \"$f\" not found"; exit 1; fi
   # check input is a fastq
-  if [[ $f != *.bam ]]; then echo "input is not a bam file"; exit 1; fi
+  if [[ $f != *.bam ]]; then >&2 echo "input is not a bam file"; exit 1; fi
   
-  BASE="$(basename $f)"
+  BASE="$(basename $INPUT)"
   OUTPUT=${BASE}.samstats
   
   samtools stats $INPUT > $OUTPUT
